language: node_js
node_js: 8
sudo: required
dist: trusty
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
before_script:
- npm install -g codeclimate-test-reporter
- npm i
script:
- npm t
- codeclimate-test-reporter < ./coverage/lcov.info
