service: planMyDay
custom: ${file(./environment.yml)} 
provider:
  name: aws
  runtime: nodejs6.10
  deploymentBucket: ${self:custom.S3_DEPLOY_BUCKET}
  stage: dev
  region: eu-west-1

  environment:
    TODOIST_PROJECTS: ${self:custom.TODOIST_PROJECTS}
    TODOIST_API_TOKEN: ${self:custom.TODOIST_API_TOKEN}

package:
 exclude:
   - coverage/**
   - __tests__/**
   - docs/**

functions:
  planMyDay:
    handler: handler.planMyDay
    events:
      - schedule: cron(0 8 * * ? *)