service: planMyDay
custom: ${file(./environment.yml)} 
provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: eu-east-1

  environment:
    TODOIST_PROJECTS: ${self:custom.TODOIST_PROJECTS}
    TODOIST_API_TOKEN: ${self:custom.TODOIST_API_TOKEN}

# you can add packaging information here
package:
#  include:
#    - include-me.js
#    - include-me-dir/**
 exclude:
   - coverage/**
   - __tests__/**

functions:
  planMyDay:
    handler: handler.planMyDay
    events:
      - schedule: cron(0 8 * * ? *)